### ISSUE TITLE
apache-stats.py causes IndexError on Ubuntu 16.04 Apache 2.4

### ISSUE THREAD

**Issue by jrhoades** [librenms/librenms-agent#95]
Hi,

When I run apache-stats.py on my Ubuntu 16.04/Apache 2.4 server I get this error:

>
> Traceback (most recent call last):
>   File "/etc/snmp/apache-stats.py", line 67, in <module>
>     params[fields[0]] = fields[1]
> IndexError: list index out of range
> 

Looking at the output of server-status, I can see that not every line follows  "key : value".

My inelegant solution was to add a try catch block starting line 61:
```
	else:
		# just store everything else
		params[fields[0]] = fields[1]

```
```
        else:
                # just store everything else
                try:
                        params[fields[0]] = fields[1]
                except:
                        params[fields[0]] = ''
```

**Comment by NeonHorizon** [comment]
I just ran into this as well and came up with a slightly different solution I changed:

`else:
		# just store everything else
		params[fields[0]] = fields[1]
`
to
`elseif len(fields) > 1:
		# just store everything else
		params[fields[0]] = fields[1]
`

Mine differs from yours in that it completely omits the parameter from the array, I don't think thats an issue since it doesn't presume all the parameters are there?
If it is I guess a final else: with a params[fields[0]] = '' like yours would do it.

**Comment by laf** [comment]
@NeonHorizon Would you be happy to submit a pull request?

**Comment by NeonHorizon** [comment]
Yeah sure, I've only just installed LibreNMS so let me do some testing first...
